### ISSUE TITLE
Comments on same line as hosts entry are not colored

### ISSUE THREAD

**Issue by dcrusader** [tommasov/hosts#1]
Placing comments on the same line as a hosts entry does not appear to trigger comment coloring.

    127.0.0.1       www.sample.com # same line comment not colored

![image](https://user-images.githubusercontent.com/20330/35638578-454301e2-066c-11e8-81a1-3f3623fe8ef4.png)

Thanks for this extension, by the way. 👍

**Comment by Tommasov** [comment]
Fixing. **Thank you**

**Comment by Tommasov** [comment]
Fixed
